---
# file: roles/elasticsearch/tasks/elasticsearch.yml

- name: install latest latest elasticsearch and openjdk jre packages
  sudo: yes
  apt: pkg={{item}} state=latest
  with_items:
    - elasticsearch

- name: make sure elasticsearch is running
  sudo: yes
  service: name=elasticsearch state=running
